USE medical_clinic;

-- Inserting data into USERS
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (1, 'karen.lee1', 'hashed_pwd_1', 'Admin', 'Karen', 'Lee');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (2, 'sarah.wilson2', 'hashed_pwd_2', 'Admin', 'Sarah', 'Wilson');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (3, 'thomas.zazai3', 'hashed_pwd_3', 'Admin', 'Thomas', 'Zazai');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (4, 'richard.harris4', 'hashed_pwd_4', 'Admin', 'Richard', 'Harris');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (5, 'mark.afridi5', 'hashed_pwd_5', 'Admin', 'Mark', 'Afridi');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (6, 'charles.wilson6', 'hashed_pwd_6', 'Receptionist', 'Charles', 'Wilson');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (7, 'christopher.anderson7', 'hashed_pwd_7', 'Receptionist', 'Christopher', 'Anderson');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (8, 'nancy.gonzalez8', 'hashed_pwd_8', 'Receptionist', 'Nancy', 'Gonzalez');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (9, 'daniel.afridi9', 'hashed_pwd_9', 'Receptionist', 'Daniel', 'Afridi');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (10, 'sarah.robinson10', 'hashed_pwd_10', 'Receptionist', 'Sarah', 'Robinson');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (11, 'christopher.thompson11', 'hashed_pwd_11', 'Receptionist', 'Christopher', 'Thompson');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (12, 'david.wilson12', 'hashed_pwd_12', 'Receptionist', 'David', 'Wilson');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (13, 'patricia.gonzalez13', 'hashed_pwd_13', 'Receptionist', 'Patricia', 'Gonzalez');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (14, 'christopher.davis14', 'hashed_pwd_14', 'Receptionist', 'Christopher', 'Davis');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (15, 'betty.moore15', 'hashed_pwd_15', 'Receptionist', 'Betty', 'Moore');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (16, 'michael.hernandez16', 'hashed_pwd_16', 'Receptionist', 'Michael', 'Hernandez');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (17, 'thomas.rodriguez17', 'hashed_pwd_17', 'Receptionist', 'Thomas', 'Rodriguez');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (18, 'mark.ramirez18', 'hashed_pwd_18', 'Receptionist', 'Mark', 'Ramirez');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (19, 'mary.smith19', 'hashed_pwd_19', 'Receptionist', 'Mary', 'Smith');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (20, 'margaret.thomas20', 'hashed_pwd_20', 'Receptionist', 'Margaret', 'Thomas');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (21, 'nancy.clark21', 'hashed_pwd_21', 'Receptionist', 'Nancy', 'Clark');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (22, 'patricia.thompson22', 'hashed_pwd_22', 'Receptionist', 'Patricia', 'Thompson');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (23, 'sarah.afridi23', 'hashed_pwd_23', 'Receptionist', 'Sarah', 'Afridi');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (24, 'daniel.ramirez24', 'hashed_pwd_24', 'Receptionist', 'Daniel', 'Ramirez');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (25, 'sarah.brown25', 'hashed_pwd_25', 'Receptionist', 'Sarah', 'Brown');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (26, 'michael.thomas26', 'hashed_pwd_26', 'Receptionist', 'Michael', 'Thomas');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (27, 'christopher.davis27', 'hashed_pwd_27', 'Receptionist', 'Christopher', 'Davis');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (28, 'michael.moore28', 'hashed_pwd_28', 'Receptionist', 'Michael', 'Moore');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (29, 'christopher.perez29', 'hashed_pwd_29', 'Receptionist', 'Christopher', 'Perez');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (30, 'jennifer.miller30', 'hashed_pwd_30', 'Receptionist', 'Jennifer', 'Miller');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (31, 'jennifer.lopez31', 'hashed_pwd_31', 'Receptionist', 'Jennifer', 'Lopez');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (32, 'mark.thomas32', 'hashed_pwd_32', 'Receptionist', 'Mark', 'Thomas');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (33, 'susan.harris33', 'hashed_pwd_33', 'Receptionist', 'Susan', 'Harris');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (34, 'nancy.taylor34', 'hashed_pwd_34', 'Receptionist', 'Nancy', 'Taylor');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (35, 'karen.martinez35', 'hashed_pwd_35', 'Receptionist', 'Karen', 'Martinez');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (36, 'sandra.zazai36', 'hashed_pwd_36', 'Receptionist', 'Sandra', 'Zazai');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (37, 'linda.sanchez37', 'hashed_pwd_37', 'Receptionist', 'Linda', 'Sanchez');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (38, 'john.garcia38', 'hashed_pwd_38', 'Receptionist', 'John', 'Garcia');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (39, 'idrees.harris39', 'hashed_pwd_39', 'Receptionist', 'Idrees', 'Harris');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (40, 'karen.clark40', 'hashed_pwd_40', 'Receptionist', 'Karen', 'Clark');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (41, 'betty.taylor41', 'hashed_pwd_41', 'Receptionist', 'Betty', 'Taylor');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (42, 'patricia.davis42', 'hashed_pwd_42', 'Receptionist', 'Patricia', 'Davis');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (43, 'betty.thompson43', 'hashed_pwd_43', 'Receptionist', 'Betty', 'Thompson');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (44, 'john.moore44', 'hashed_pwd_44', 'Receptionist', 'John', 'Moore');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (45, 'david.thomas45', 'hashed_pwd_45', 'Receptionist', 'David', 'Thomas');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (46, 'patricia.jackson46', 'hashed_pwd_46', 'Receptionist', 'Patricia', 'Jackson');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (47, 'lisa.white47', 'hashed_pwd_47', 'Receptionist', 'Lisa', 'White');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (48, 'nancy.perez48', 'hashed_pwd_48', 'Receptionist', 'Nancy', 'Perez');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (49, 'sandra.white49', 'hashed_pwd_49', 'Receptionist', 'Sandra', 'White');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (50, 'linda.anderson50', 'hashed_pwd_50', 'Receptionist', 'Linda', 'Anderson');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (51, 'sandra.robinson51', 'hashed_pwd_51', 'Receptionist', 'Sandra', 'Robinson');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (52, 'joseph.miller52', 'hashed_pwd_52', 'Receptionist', 'Joseph', 'Miller');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (53, 'margaret.garcia53', 'hashed_pwd_53', 'Receptionist', 'Margaret', 'Garcia');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (54, 'patricia.garcia54', 'hashed_pwd_54', 'Receptionist', 'Patricia', 'Garcia');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (55, 'sandra.thomas55', 'hashed_pwd_55', 'Receptionist', 'Sandra', 'Thomas');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (56, 'susan.gonzalez56', 'hashed_pwd_56', 'Receptionist', 'Susan', 'Gonzalez');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (57, 'farman.ramirez57', 'hashed_pwd_57', 'Receptionist', 'Farman', 'Ramirez');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (58, 'susan.rodriguez58', 'hashed_pwd_58', 'Receptionist', 'Susan', 'Rodriguez');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (59, 'mary.lee59', 'hashed_pwd_59', 'Receptionist', 'Mary', 'Lee');
INSERT INTO USERS (user_id, username, password_hash, role, first_name, last_name) VALUES (60, 'david.robinson60', 'hashed_pwd_60', 'Receptionist', 'David', 'Robinson');

-- Inserting data into PATIENTS
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (1, 'David', 'Zazai', '2013-06-12', 'Female', '555-494-5216');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (2, 'Jessica', 'Garcia', '1967-08-06', 'Male', '555-633-9696');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (3, 'William', 'Lee', '1965-10-18', 'Female', '555-296-4080');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (4, 'Charles', 'Rodriguez', '1954-10-11', 'Female', '555-708-4731');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (5, 'John', 'Thomas', '2007-03-30', 'Female', '555-647-9196');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (6, 'Jennifer', 'Brown', '1967-06-18', 'Female', '555-709-9381');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (7, 'Daniel', 'Thompson', '2007-02-19', 'Male', '555-670-4268');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (8, 'Susan', 'Wilson', '1976-11-12', 'Female', '555-163-7344');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (9, 'Idrees', 'White', '2012-04-15', 'Female', '555-781-1727');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (10, 'Jessica', 'Anderson', '2008-07-25', 'Male', '555-142-6098');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (11, 'Charles', 'Miller', '1988-03-17', 'Male', '555-623-3136');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (12, 'Jessica', 'Afridi', '1984-12-17', 'Female', '555-705-9301');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (13, 'Joseph', 'Jackson', '1981-12-18', 'Male', '555-394-5555');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (14, 'Joseph', 'Garcia', '2002-07-01', 'Male', '555-927-5593');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (15, 'Susan', 'Martin', '1971-03-25', 'Male', '555-352-8190');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (16, 'Idrees', 'Williams', '2014-10-10', 'Female', '555-302-3919');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (17, 'Patricia', 'Afridi', '1957-03-05', 'Male', '555-532-3310');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (18, 'Robert', 'White', '2009-04-21', 'Male', '555-548-7465');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (19, 'Richard', 'Davis', '1954-04-11', 'Male', '555-605-3387');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (20, 'Charles', 'Sanchez', '1974-09-29', 'Female', '555-342-1192');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (21, 'Sarah', 'Robinson', '1971-10-28', 'Female', '555-696-9030');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (22, 'Charles', 'Smith', '2003-07-09', 'Male', '555-530-4620');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (23, 'Lisa', 'Lewis', '2005-08-20', 'Female', '555-577-7471');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (24, 'Nancy', 'Martin', '2011-08-01', 'Male', '555-729-8444');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (25, 'John', 'White', '1990-10-31', 'Female', '555-845-2244');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (26, 'Idrees', 'Williams', '1996-07-12', 'Male', '555-750-5321');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (27, 'Richard', 'White', '1978-03-02', 'Female', '555-804-5165');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (28, 'Betty', 'Ramirez', '1990-01-03', 'Female', '555-843-7581');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (29, 'Robert', 'Williams', '1959-01-07', 'Male', '555-765-9758');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (30, 'William', 'Anderson', '1954-06-28', 'Female', '555-724-3551');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (31, 'Thomas', 'Perez', '1972-10-05', 'Female', '555-808-3268');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (32, 'Betty', 'Williams', '1956-08-01', 'Male', '555-652-1742');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (33, 'Christopher', 'Brown', '1952-02-12', 'Female', '555-549-2818');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (34, 'Lisa', 'Harris', '2006-07-31', 'Male', '555-105-9555');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (35, 'Mary', 'Lopez', '1967-08-12', 'Female', '555-978-9221');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (36, 'Mark', 'Moore', '2008-04-01', 'Female', '555-808-7102');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (37, 'Barbara', 'Harris', '1995-08-31', 'Male', '555-392-3601');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (38, 'Mark', 'Jackson', '1997-01-15', 'Male', '555-196-2440');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (39, 'Margaret', 'Smith', '2014-04-24', 'Male', '555-942-5456');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (40, 'Sandra', 'Zazai', '2006-11-19', 'Female', '555-608-1876');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (41, 'Richard', 'Miller', '2011-01-20', 'Female', '555-522-7633');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (42, 'Michael', 'Martin', '2014-02-14', 'Male', '555-489-3206');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (43, 'Robert', 'Afridi', '2013-01-12', 'Female', '555-625-8802');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (44, 'Idrees', 'Brown', '2002-04-25', 'Female', '555-678-6115');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (45, 'Barbara', 'Zazai', '1994-02-14', 'Female', '555-593-6607');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (46, 'James', 'Taylor', '1976-03-25', 'Male', '555-361-9934');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (47, 'Sandra', 'Lewis', '1959-07-21', 'Female', '555-250-1008');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (48, 'William', 'Lewis', '1985-05-06', 'Female', '555-134-4201');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (49, 'Elizabeth', 'Johnson', '1955-10-28', 'Female', '555-767-9049');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (50, 'Idrees', 'Taylor', '1968-10-23', 'Male', '555-937-2655');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (51, 'James', 'Afridi', '2010-12-07', 'Male', '555-705-2348');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (52, 'Robert', 'Jackson', '2004-07-19', 'Female', '555-934-6988');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (53, 'Margaret', 'Lewis', '2011-08-21', 'Female', '555-502-7844');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (54, 'Christopher', 'Jones', '1991-01-22', 'Male', '555-810-6229');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (55, 'Idrees', 'Lewis', '1988-01-29', 'Male', '555-248-1588');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (56, 'Christopher', 'Anderson', '2006-11-18', 'Male', '555-213-2743');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (57, 'Anthony', 'Smith', '1961-02-15', 'Male', '555-329-6826');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (58, 'Idrees', 'Martinez', '1965-10-04', 'Male', '555-700-6136');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (59, 'Susan', 'Davis', '1961-02-05', 'Female', '555-692-2518');
INSERT INTO PATIENTS (patient_id, first_name, last_name, dob, gender, contact) VALUES (60, 'Matthew', 'Afridi', '1951-10-30', 'Male', '555-186-1081');

-- Inserting data into DOCTORS
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (1, 'Linda', 'Zazai', 'Orthopedics', '555-DOC-9016', 'Room 128');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (2, 'Joseph', 'Robinson', 'Ophthalmology', '555-DOC-6643', 'Room 160');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (3, 'David', 'Lewis', 'Neurology', '555-DOC-3554', 'Room 179');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (4, 'Robert', 'Wilson', 'Psychiatry', '555-DOC-4088', 'Room 122');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (5, 'Robert', 'Martinez', 'Cardiology', '555-DOC-8848', 'Room 332');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (6, 'Patricia', 'Zazai', 'Pediatrics', '555-DOC-5496', 'Room 103');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (7, 'David', 'Garcia', 'Cardiology', '555-DOC-9191', 'Room 172');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (8, 'Daniel', 'Moore', 'Ophthalmology', '555-DOC-4808', 'Room 361');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (9, 'Thomas', 'Sanchez', 'Dermatology', '555-DOC-9176', 'Room 243');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (10, 'Linda', 'Hernandez', 'Ophthalmology', '555-DOC-8775', 'Room 244');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (11, 'David', 'Brown', 'General Practice', '555-DOC-4022', 'Room 385');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (12, 'Nancy', 'Wilson', 'Pediatrics', '555-DOC-4578', 'Room 219');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (13, 'Anthony', 'Brown', 'Psychiatry', '555-DOC-8126', 'Room 181');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (14, 'Idrees', 'Smith', 'Ophthalmology', '555-DOC-9944', 'Room 391');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (15, 'James', 'Lopez', 'Ophthalmology', '555-DOC-5296', 'Room 115');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (16, 'Charles', 'Gonzalez', 'Cardiology', '555-DOC-8977', 'Room 291');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (17, 'Joseph', 'Ramirez', 'Pediatrics', '555-DOC-3507', 'Room 259');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (18, 'Karen', 'Davis', 'Radiology', '555-DOC-8649', 'Room 230');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (19, 'David', 'Davis', 'Radiology', '555-DOC-9396', 'Room 316');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (20, 'Nancy', 'Hernandez', 'Orthopedics', '555-DOC-7803', 'Room 326');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (21, 'Christopher', 'Williams', 'Orthopedics', '555-DOC-4023', 'Room 244');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (22, 'Jennifer', 'Williams', 'Neurology', '555-DOC-3062', 'Room 207');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (23, 'Anthony', 'Williams', 'Cardiology', '555-DOC-7519', 'Room 276');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (24, 'William', 'Garcia', 'General Practice', '555-DOC-7782', 'Room 266');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (25, 'Patricia', 'Garcia', 'Psychiatry', '555-DOC-2979', 'Room 172');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (26, 'Farman', 'Clark', 'Pediatrics', '555-DOC-4539', 'Room 157');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (27, 'Barbara', 'Clark', 'Ophthalmology', '555-DOC-8890', 'Room 323');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (28, 'Matthew', 'Davis', 'Radiology', '555-DOC-1762', 'Room 166');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (29, 'Thomas', 'Brown', 'Oncology', '555-DOC-7861', 'Room 219');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (30, 'Susan', 'Lewis', 'Orthopedics', '555-DOC-3338', 'Room 317');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (31, 'Susan', 'Lee', 'Oncology', '555-DOC-6560', 'Room 325');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (32, 'John', 'Robinson', 'Cardiology', '555-DOC-6924', 'Room 353');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (33, 'Patricia', 'Thomas', 'Orthopedics', '555-DOC-7451', 'Room 361');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (34, 'Anthony', 'Thompson', 'Pediatrics', '555-DOC-3470', 'Room 130');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (35, 'Mary', 'Zazai', 'Cardiology', '555-DOC-3455', 'Room 239');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (36, 'John', 'Harris', 'Radiology', '555-DOC-1163', 'Room 187');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (37, 'Joseph', 'Taylor', 'Dermatology', '555-DOC-3202', 'Room 191');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (38, 'Nancy', 'Martinez', 'Ophthalmology', '555-DOC-6020', 'Room 187');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (39, 'Linda', 'Hernandez', 'Radiology', '555-DOC-8902', 'Room 316');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (40, 'Thomas', 'Robinson', 'Oncology', '555-DOC-5145', 'Room 309');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (41, 'Joseph', 'Afridi', 'Neurology', '555-DOC-1136', 'Room 392');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (42, 'Nancy', 'Davis', 'Oncology', '555-DOC-6609', 'Room 251');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (43, 'Elizabeth', 'Afridi', 'Neurology', '555-DOC-2206', 'Room 119');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (44, 'Betty', 'Gonzalez', 'Neurology', '555-DOC-1299', 'Room 261');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (45, 'Lisa', 'Gonzalez', 'Pediatrics', '555-DOC-1350', 'Room 118');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (46, 'Mark', 'Jackson', 'Psychiatry', '555-DOC-8207', 'Room 178');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (47, 'Margaret', 'Smith', 'Orthopedics', '555-DOC-1297', 'Room 184');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (48, 'Jessica', 'Robinson', 'Dermatology', '555-DOC-8754', 'Room 167');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (49, 'Margaret', 'Moore', 'Cardiology', '555-DOC-9683', 'Room 275');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (50, 'Jessica', 'Clark', 'Cardiology', '555-DOC-7094', 'Room 233');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (51, 'David', 'Lewis', 'Cardiology', '555-DOC-7888', 'Room 275');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (52, 'Michael', 'Martinez', 'Pediatrics', '555-DOC-9869', 'Room 161');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (53, 'Joseph', 'Clark', 'Oncology', '555-DOC-6030', 'Room 177');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (54, 'Lisa', 'Davis', 'General Practice', '555-DOC-3520', 'Room 324');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (55, 'Susan', 'Afridi', 'Pediatrics', '555-DOC-4457', 'Room 341');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (56, 'Michael', 'Brown', 'Ophthalmology', '555-DOC-2172', 'Room 278');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (57, 'Betty', 'Williams', 'Psychiatry', '555-DOC-5064', 'Room 278');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (58, 'Mark', 'Rodriguez', 'Dermatology', '555-DOC-9142', 'Room 143');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (59, 'Margaret', 'Lee', 'Ophthalmology', '555-DOC-7409', 'Room 152');
INSERT INTO DOCTORS (doctor_id, first_name, last_name, specialty, contact, room_number) VALUES (60, 'Jennifer', 'Rodriguez', 'General Practice', '555-DOC-6010', 'Room 342');

-- Inserting data into MEDICAL_SERVICES
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (1, 'Consultation', 50.0);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (2, 'Blood Test', 25.0);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (3, 'X-Ray', 100.0);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (4, 'MRI Scan', 400.0);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (5, 'ECG', 75.0);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (6, 'Ultrasound', 150.0);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (7, 'Vaccination', 30.0);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (8, 'Physical Therapy', 80.0);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (9, 'Specialized Test 9', 89.05);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (10, 'Specialized Test 10', 205.31);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (11, 'Specialized Test 11', 473.28);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (12, 'Specialized Test 12', 60.65);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (13, 'Specialized Test 13', 67.01);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (14, 'Specialized Test 14', 267.98);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (15, 'Specialized Test 15', 125.62);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (16, 'Specialized Test 16', 468.92);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (17, 'Specialized Test 17', 422.2);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (18, 'Specialized Test 18', 348.66);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (19, 'Specialized Test 19', 300.83);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (20, 'Specialized Test 20', 131.93);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (21, 'Specialized Test 21', 451.88);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (22, 'Specialized Test 22', 418.15);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (23, 'Specialized Test 23', 54.49);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (24, 'Specialized Test 24', 440.67);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (25, 'Specialized Test 25', 339.43);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (26, 'Specialized Test 26', 204.56);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (27, 'Specialized Test 27', 160.79);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (28, 'Specialized Test 28', 252.5);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (29, 'Specialized Test 29', 175.36);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (30, 'Specialized Test 30', 456.45);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (31, 'Specialized Test 31', 208.28);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (32, 'Specialized Test 32', 298.82);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (33, 'Specialized Test 33', 208.66);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (34, 'Specialized Test 34', 444.09);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (35, 'Specialized Test 35', 311.58);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (36, 'Specialized Test 36', 294.87);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (37, 'Specialized Test 37', 494.46);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (38, 'Specialized Test 38', 123.21);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (39, 'Specialized Test 39', 97.22);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (40, 'Specialized Test 40', 248.86);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (41, 'Specialized Test 41', 62.86);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (42, 'Specialized Test 42', 234.28);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (43, 'Specialized Test 43', 230.32);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (44, 'Specialized Test 44', 298.06);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (45, 'Specialized Test 45', 88.76);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (46, 'Specialized Test 46', 75.2);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (47, 'Specialized Test 47', 439.49);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (48, 'Specialized Test 48', 355.78);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (49, 'Specialized Test 49', 287.06);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (50, 'Specialized Test 50', 157.71);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (51, 'Specialized Test 51', 357.41);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (52, 'Specialized Test 52', 98.82);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (53, 'Specialized Test 53', 123.92);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (54, 'Specialized Test 54', 353.0);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (55, 'Specialized Test 55', 358.13);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (56, 'Specialized Test 56', 88.89);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (57, 'Specialized Test 57', 380.05);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (58, 'Specialized Test 58', 142.37);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (59, 'Specialized Test 59', 443.33);
INSERT INTO MEDICAL_SERVICES (service_id, service_name, price) VALUES (60, 'Specialized Test 60', 232.92);

-- Inserting data into VISITS
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (1, 57, 1, '2023-09-29 16:00:00', 'Hypertension');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (2, 35, 6, '2023-03-17 09:00:00', 'Anemia');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (3, 2, 17, '2023-04-26 10:00:00', 'Sprained Ankle');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (4, 6, 50, '2023-08-14 12:00:00', 'Acid Reflux');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (5, 42, 14, '2023-03-18 15:00:00', 'Flu');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (6, 40, 9, '2023-08-01 16:00:00', 'Asthma');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (7, 20, 60, '2023-06-14 08:00:00', 'Migraine');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (8, 59, 40, '2023-01-15 10:00:00', 'Acid Reflux');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (9, 50, 56, '2023-12-07 09:00:00', 'Healthy');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (10, 2, 36, '2023-09-13 10:00:00', 'Healthy');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (11, 45, 8, '2023-01-23 09:00:00', 'Healthy');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (12, 19, 15, '2023-08-06 12:00:00', 'Asthma');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (13, 1, 39, '2023-01-10 15:00:00', 'Migraine');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (14, 27, 13, '2023-08-02 16:00:00', 'Diabetes Type 2');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (15, 5, 10, '2023-03-20 15:00:00', 'Common Cold');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (16, 44, 12, '2023-10-26 13:00:00', 'Hypertension');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (17, 45, 58, '2023-11-30 14:00:00', 'Common Cold');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (18, 50, 5, '2023-12-14 14:00:00', 'Sprained Ankle');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (19, 55, 29, '2023-08-15 12:00:00', 'Migraine');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (20, 34, 42, '2023-01-15 15:00:00', 'Acid Reflux');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (21, 48, 56, '2023-06-08 14:00:00', 'Diabetes Type 2');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (22, 20, 17, '2023-06-02 14:00:00', 'Hypertension');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (23, 60, 14, '2023-03-24 15:00:00', 'Hypertension');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (24, 6, 40, '2023-01-16 17:00:00', 'Sprained Ankle');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (25, 28, 33, '2023-09-25 15:00:00', 'Healthy');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (26, 7, 55, '2023-10-29 12:00:00', 'Common Cold');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (27, 40, 58, '2023-10-11 10:00:00', 'Anemia');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (28, 53, 54, '2023-07-25 09:00:00', 'Anemia');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (29, 2, 26, '2023-01-05 09:00:00', 'Acid Reflux');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (30, 47, 17, '2023-06-24 17:00:00', 'Anemia');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (31, 45, 40, '2023-12-20 10:00:00', 'Anemia');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (32, 26, 37, '2023-06-16 10:00:00', 'Hypertension');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (33, 60, 35, '2023-11-22 10:00:00', 'Asthma');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (34, 6, 9, '2023-12-19 17:00:00', 'Healthy');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (35, 34, 60, '2023-07-11 15:00:00', 'Diabetes Type 2');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (36, 40, 4, '2023-08-06 09:00:00', 'Anemia');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (37, 35, 36, '2023-08-10 17:00:00', 'Anemia');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (38, 4, 28, '2023-08-25 09:00:00', 'Hypertension');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (39, 23, 36, '2023-07-17 15:00:00', 'Asthma');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (40, 12, 29, '2023-03-24 17:00:00', 'Common Cold');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (41, 34, 1, '2023-11-27 09:00:00', 'Sprained Ankle');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (42, 28, 58, '2023-12-29 12:00:00', 'Sprained Ankle');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (43, 32, 33, '2023-01-02 13:00:00', 'Anemia');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (44, 3, 47, '2023-09-30 15:00:00', 'Migraine');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (45, 47, 15, '2023-07-18 15:00:00', 'Diabetes Type 2');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (46, 54, 26, '2023-11-26 16:00:00', 'Healthy');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (47, 5, 42, '2023-05-01 12:00:00', 'Acid Reflux');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (48, 43, 5, '2023-05-09 10:00:00', 'Migraine');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (49, 21, 58, '2023-03-24 09:00:00', 'Sprained Ankle');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (50, 17, 35, '2023-02-01 16:00:00', 'Sprained Ankle');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (51, 30, 49, '2023-09-05 13:00:00', 'Anemia');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (52, 58, 54, '2023-03-04 17:00:00', 'Migraine');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (53, 3, 22, '2023-10-02 14:00:00', 'Anemia');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (54, 20, 43, '2023-05-04 17:00:00', 'Common Cold');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (55, 16, 22, '2023-07-19 12:00:00', 'Flu');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (56, 47, 43, '2023-07-20 12:00:00', 'Common Cold');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (57, 42, 7, '2023-09-08 15:00:00', 'Flu');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (58, 3, 27, '2023-11-26 10:00:00', 'Flu');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (59, 16, 53, '2023-12-23 09:00:00', 'Acid Reflux');
INSERT INTO VISITS (visit_id, patient_id, doctor_id, visit_date, diagnosis) VALUES (60, 10, 40, '2023-06-07 15:00:00', 'Anemia');

-- Inserting data into PRESCRIPTIONS
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (1, 29, 'Amlodipine', '20mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (2, 42, 'Paracetamol', '10mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (3, 44, 'Metformin', '50mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (4, 22, 'Amlodipine', '20mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (5, 17, 'Albuterol', '20mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (6, 37, 'Metformin', '50mg', 'Take once daily');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (7, 58, 'Ibuprofen', '200mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (8, 27, 'Amoxicillin', '10mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (9, 44, 'Amoxicillin', '500mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (10, 12, 'Losartan', '500mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (11, 16, 'Omeprazole', '50mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (12, 29, 'Atorvastatin', '500mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (13, 12, 'Gabapentin', '200mg', 'Take once daily');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (14, 4, 'Omeprazole', '10mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (15, 46, 'Lisinopril', '20mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (16, 50, 'Omeprazole', '500mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (17, 6, 'Losartan', '20mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (18, 10, 'Lisinopril', '500mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (19, 26, 'Atorvastatin', '200mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (20, 30, 'Ibuprofen', '200mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (21, 16, 'Paracetamol', '20mg', 'Take once daily');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (22, 47, 'Paracetamol', '20mg', 'Take once daily');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (23, 4, 'Albuterol', '20mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (24, 3, 'Metformin', '20mg', 'Take once daily');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (25, 12, 'Metformin', '500mg', 'Take once daily');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (26, 23, 'Amlodipine', '50mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (27, 27, 'Atorvastatin', '20mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (28, 11, 'Atorvastatin', '200mg', 'Take once daily');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (29, 4, 'Amlodipine', '20mg', 'Take once daily');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (30, 1, 'Omeprazole', '10mg', 'Take once daily');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (31, 24, 'Atorvastatin', '200mg', 'Take once daily');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (32, 34, 'Lisinopril', '500mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (33, 54, 'Losartan', '50mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (34, 55, 'Paracetamol', '500mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (35, 19, 'Lisinopril', '200mg', 'Take once daily');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (36, 51, 'Albuterol', '50mg', 'Take once daily');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (37, 42, 'Amlodipine', '10mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (38, 42, 'Lisinopril', '500mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (39, 14, 'Paracetamol', '50mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (40, 18, 'Lisinopril', '10mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (41, 15, 'Ibuprofen', '10mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (42, 37, 'Amoxicillin', '50mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (43, 47, 'Gabapentin', '500mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (44, 14, 'Paracetamol', '500mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (45, 24, 'Amoxicillin', '500mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (46, 18, 'Albuterol', '50mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (47, 34, 'Metformin', '20mg', 'Take once daily');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (48, 53, 'Ibuprofen', '500mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (49, 18, 'Omeprazole', '50mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (50, 30, 'Amoxicillin', '200mg', 'Take once daily');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (51, 40, 'Metformin', '10mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (52, 37, 'Lisinopril', '50mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (53, 29, 'Metformin', '500mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (54, 43, 'Omeprazole', '20mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (55, 47, 'Losartan', '500mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (56, 4, 'Albuterol', '20mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (57, 53, 'Gabapentin', '10mg', 'Take once daily');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (58, 60, 'Gabapentin', '50mg', 'Take twice daily after meals');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (59, 44, 'Metformin', '10mg', 'Take as needed for pain');
INSERT INTO PRESCRIPTIONS (prescription_id, visit_id, medicine_name, dosage, instructions) VALUES (60, 2, 'Amlodipine', '20mg', 'Take as needed for pain');

-- Inserting data into VISIT_SERVICES
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (1, 30, 47);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (2, 32, 1);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (3, 13, 42);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (4, 22, 16);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (5, 50, 21);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (6, 60, 23);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (7, 39, 35);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (8, 6, 6);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (9, 9, 25);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (10, 52, 28);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (11, 12, 28);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (12, 56, 31);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (13, 14, 22);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (14, 32, 55);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (15, 7, 38);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (16, 1, 34);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (17, 15, 30);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (18, 3, 11);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (19, 1, 33);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (20, 32, 51);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (21, 40, 49);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (22, 14, 47);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (23, 53, 49);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (24, 34, 10);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (25, 41, 14);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (26, 6, 13);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (27, 17, 23);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (28, 18, 21);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (29, 32, 2);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (30, 18, 54);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (31, 44, 2);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (32, 56, 42);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (33, 22, 53);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (34, 37, 59);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (35, 59, 59);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (36, 51, 50);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (37, 44, 35);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (38, 40, 26);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (39, 48, 3);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (40, 52, 2);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (41, 59, 52);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (42, 12, 13);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (43, 13, 22);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (44, 42, 23);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (45, 1, 53);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (46, 22, 14);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (47, 5, 43);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (48, 25, 45);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (49, 36, 9);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (50, 24, 10);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (51, 42, 29);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (52, 57, 37);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (53, 26, 13);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (54, 5, 57);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (55, 57, 24);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (56, 48, 10);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (57, 6, 18);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (58, 47, 57);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (59, 48, 59);
INSERT INTO VISIT_SERVICES (vs_id, visit_id, service_id) VALUES (60, 34, 14);

-- Inserting data into BILLS
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (1, 1, 558.49, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (2, 2, 135.53, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (3, 3, 62.53, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (4, 4, 56.95, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (5, 5, 250.35, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (6, 6, 681.46, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (7, 7, 65.91, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (8, 8, 70.62, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (9, 9, 73.4, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (10, 10, 93.72, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (11, 11, 138.38, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (12, 12, 293.86, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (13, 13, 335.2, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (14, 14, 368.37, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (15, 15, 167.02, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (16, 16, 50.11, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (17, 17, 164.66, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (18, 18, 141.68, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (19, 19, 128.37, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (20, 20, 73.23, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (21, 21, 92.38, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (22, 22, 441.38, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (23, 23, 132.79, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (24, 24, 59.79, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (25, 25, 232.91, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (26, 26, 37.27, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (27, 27, 137.55, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (28, 28, 147.06, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (29, 29, 104.13, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (30, 30, 291.44, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (31, 31, 121.01, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (32, 32, 673.14, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (33, 33, 62.22, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (34, 34, 359.36, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (35, 35, 107.11, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (36, 36, 88.4, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (37, 37, 105.52, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (38, 38, 87.54, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (39, 39, 155.24, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (40, 40, 207.5, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (41, 41, 129.27, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (42, 42, 330.04, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (43, 43, 100.87, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (44, 44, 247.85, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (45, 45, 80.97, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (46, 46, 108.87, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (47, 47, 68.13, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (48, 48, 407.26, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (49, 49, 121.69, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (50, 50, 190.35, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (51, 51, 83.19, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (52, 52, 484.4, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (53, 53, 40.72, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (54, 54, 85.47, 'Unpaid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (55, 55, 82.93, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (56, 56, 210.03, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (57, 57, 298.79, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (58, 58, 138.66, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (59, 59, 233.66, 'Paid');
INSERT INTO BILLS (bill_id, visit_id, total_amount, status) VALUES (60, 60, 161.81, 'Paid');

